-- MySQL Script generated by MySQL Workbench
-- Bat 28 Uya 2020 02:12:35 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema flash_cards
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `flash_cards` ;

-- -----------------------------------------------------
-- Schema flash_cards
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `flash_cards` ;
USE `flash_cards` ;

-- -----------------------------------------------------
-- Table `flash_cards`.`folder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flash_cards`.`folder` (
  `folder_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`folder_id`),
  UNIQUE INDEX `folder_id_UNIQUE` (`folder_id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `flash_cards`.`card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flash_cards`.`card` (
  `card_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `body` TEXT NULL,
  `create_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `folder_id` INT NOT NULL,
  PRIMARY KEY (`card_id`),
  UNIQUE INDEX `id_UNIQUE` (`card_id` ASC) VISIBLE,
  INDEX `folder_fk_idx` (`folder_id` ASC) VISIBLE,
  CONSTRAINT `folder_fk`
    FOREIGN KEY (`folder_id`)
    REFERENCES `flash_cards`.`folder` (`folder_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
